#服务器端口
server:
  port: 8104

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.statistics.dev.url}
    username: ${blade.datasource.statistics.dev.username}
    password: ${blade.datasource.statistics.dev.password}
