#服务器端口
server:
  port: 8123

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.wechat.dev.url}
    username: ${blade.datasource.wechat.dev.username}
    password: ${blade.datasource.wechat.dev.password}