#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:com/ai/apac/smartenv/**/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ai.apac.smartenv.**.entity

#swagger扫描路径配置
swagger:
  base-packages:
    - org.springbalde
    - com.ai.apac.smartenv