#服务器端口
server:
  port: 8103

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.log.dev.url}
    username: ${blade.datasource.log.dev.username}
    password: ${blade.datasource.log.dev.password}
