#spring配置
spring:
  jackson:
    time-zone: GMT+8
  redis:
    ##redis 单机环境配置
    #host: redis-sentinel-master-ss
    #host: 182.43.208.247
    #port: 6379
    #password:
    #database: 0
    #ssl: false
    ##redis 集群环境配置
    #cluster:
    #  nodes: redis-sentinel-sentinel-ss:26379
    #  commandTimeout: 5000
    #  password:
    #  database: 0
    #  ssl: false
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: redis-sentinel-sentinel-ss:26379
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: org.postgresql.Driver
    #driver-class-name: oracle.jdbc.OracleDriver
    druid:
      initial-size: 5
      max-active: 100
      min-idle: 5
      # MySql、PostgreSQL校验
      validation-query: select 1
      # Oracle校验
      #validation-query: select 1 from dual
  data:
    mongodb:
      host: 172.26.98.225:27017,172.26.98.225:27018,172.26.98.225:27019
      #port: 27017
      database: smartenv
      password:
      user:
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: notice@asiainfo.sg
    password: Aisg3456&
    protocol: smtp
    test-connection: true
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.display.sendmail: 智慧环卫管理平台

  cloud:
    # Spring Cloud Stream 配置项，对应 BindingServiceProperties 类
    stream:
      # Binder 配置项，对应 BinderProperties Map
      binders:
        smartenv:
          type: rabbit # 设置 Binder 的类型
          environment: # 设置 Binder 的环境配置
            # 如果是 RabbitMQ 类型的时候，则对应的是 RabbitProperties 类
            spring:
              rabbitmq:
                #host: 172.26.98.225 # RabbitMQ 服务的地址
                #port: 5673 # RabbitMQ 服务的端口
                addresses: 172.26.98.225:5673,172.26.98.225:5674
                username: admin # RabbitMQ 服务的账号
                password: admin@123 # RabbitMQ 服务的密码
        # Binding 配置项，对应 BindingProperties Map
        smartenv-minicreate:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: 47.99.209.234:9092         #Kafka的消息中间件服务器
                      auto-create-topics: false        #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
      bindings:
        pushc-email-output:
          destination: PUSHC-TOPIC # 目的地。这里使用 RabbitMQ Exchange
          content-type: application/json # 内容格式。这里使用 JSON
          binder: smartenv # 设置使用的 Binder 名字
        pushc-email-input:
          destination: PUSHC-TOPIC # 目的地。这里使用 RabbitMQ Exchange
          content-type: application/json # 内容格式。这里使用 JSON
          binder: smartenv # 设置使用的 Binder 名字
          group: pushc-email-counsumer-group-1 # 消费者分组
        watch-position:
          destination: EXCHANGE_WATCH_LOCATION
          content-type: application/json # 内容格式。这里使用 JSON
          binder: smartenv
          consumer:
            exchangeType: topic
        vehicle-position:
          destination: EXCHANGE_VEHICLE
          binder: smartenv
          consumer:
            exchangeType: topic
        device-info:
          destination: queue
          content-type: application/json # 内容格式。这里使用 JSON
          binder: smartenv
          group: SENSOR
        minicreate-initiative-alarm-input:
          destination: lc_gps # 目的地。这里使用 Kafka Topic
          content-type: application/json # 内容格式。这里使用 JSON
          binder: smartenv-minicreate # 设置使用的 Binder 名字
          group: lc-gps-group-prod # 消费者分组
        minicreate-initiative-alarm-attachment-input:
          destination: lc_ipsfas # 目的地。这里使用 Kafka Topic
          content-type: application/json # 内容格式。这里使用 JSON
          binder: smartenv-minicreate # 设置使用的 Binder 名字
          group: lc-ipsfas-group-prod # 消费者分组
        polymerization_vehicle_change_output: # 当有紧急告警新增
          destination: polymerization_vehicle_change
          content-type: application/json # 内容格式。这里使用 JSON
          binder: smartenv
        polymerization_person_change_output: # 当有紧急告警新增
          destination: polymerization_person_change
          content-type: application/json # 内容格式。这里使用 JSON
          binder: smartenv
        watch-sos-alarm-input:
          destination: EXCHANGE_WATCH_SOS_ALARM
          content-type: application/json # 内容格式。这里使用 JSON
          binder: smartenv
          consumer:
            exchangeType: topic
          group: watchSOS-prod
#项目模块集中配置
blade:
  lock:
    mode: sentinel
    master-name: mymaster
    sentinel-address: redis://redis-sentinel-sentinel-ss:26379
    database: 0
  #多租户配置
  tenant:
    column: tenant_id
    enhance: true
    #如下租户表的租户ID根据业务实现自己维护
    exclude-tables:
      - ai_alarm_rule_info
      - ai_alarm_rule_ext
      - ai_alarm_info
      - blade_oss
  #通用开发生产环境数据库地址(特殊情况可在对应的子工程里配置覆盖)
  datasource:
    prod:
      # MySql
      url: jdbc:mysql://mysql-svc:31306/smartenv?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: smartenv
      password: smartenv@123
    flow:
      prod:
        # MySql
        url: jdbc:mysql://mysql-svc:31306/smartenv?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: smartenv
        password: smartenv@123
    log:
      prod:
        # MySql
        url: jdbc:mysql://mysql-svc:31306/smartenv_log?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
        username: smartenv
        password: smartenv@123
    wechat:
      prod:
        # MySql
        url: jdbc:mysql://mysql-svc:31306/smartenv_wechat?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
        username: smartenv
        password: smartenv@123
  document:
    resources:
      - name: 授权管理
        location: /smartenv-auth
      # - name: 工作台模块
      #   location: /smartenv-desk
      - name: 用户管理
        location: /smartenv-user
      - name: 系统管理
        location: /smartenv-system
      - name: 排班管理
        location: /smartenv-arrange
      - name: 考核管理
        location: /smartenv-assessment
      - name: 设备管理
        location: /smartenv-device
      - name: 事件管理
        location: /smartenv-event
      - name: 设施管理
        location: /smartenv-facility
      - name: 库存管理
        location: /smartenv-inventory
      - name: omnic管理
        location: /smartenv-omnic
      - name: 人员管理
        location: /smartenv-person
      - name: 统计管理
        location: /smartenv-statistic
      - name: 车辆管理
        location: /smartenv-vehicle
      - name: 工作区域管理
        location: /smartenv-workarea
      - name: 对象存储
        location: /smartenv-oss
      - name: Websocket服务
        location: /smartenv-websocket
      - name: 告警管理
        location: /smartenv-alarm
      - name: 缓存管理
        location: /smartenv-cache
      - name: 地址域管理
        location: /smartenv-address
      - name: 日志管理
        location: /blade-log
      - name: 流程管理
        location: /smartenv-flow
      - name: 微信服务
        location: /smartenv-wechat
      - name: PUSHC服务
        location: /smartenv-pushc
      - name: job服务
        location: /smartenv-job
      - name: 报表管理
        location: /smartenv-statistics

#天气API配置
weather:
  tianqiapi:
    appId: 16162243
    appSecret: PWiL9Irr

smartenv:
  app:
    baseUrl: http://smartenv-gateway

mapapi:
  config:
    bdak: 3Iaydk5GyUANuX72YQQ88O7D2E0NmiLH #百度AK
    bdJavascriptAK: hwSkU5CkNm1es5s9vzfs4LQxWDsz7ZoL
    bdsk: FIZBrfN0OpOWR7MeB1c8fS8PSc7Pid61 #百度SK
    gdkey: e6a5b6def7d6836c110d34876d76dcea #高德Key
    gdsig: 2e8c1a6a72817d5c679afd7338034665 #高德私钥
    baiduBaseUrl: http://api.map.baidu.com #百度api baseurl
    gaoDeBaseUrl: https://restapi.amap.com #高德api baseurl
    baiduGeoCovUrl: /geoconv/v1/  #百度坐标转换url
    baiduReverserGeocodingsUrl: /reverse_geocoding/v3/ #百度全球逆地理编码url
    gaodeGeoCovUrl: /v3/assistant/coordinate/convert #高德坐标转换url
    baiduStaticImageUrl: /staticimage/v2
    baiduPlaceToCoordinatesUrl: /place/v2/search #地址转坐标url

ribbon:
  ConnectTimeout: 15000 #请求连接的超时时间，默认时间为1秒
  ReadTimeout: 15000 #请求处理的超时时间

## 大数据相关配置
bigdata:
  config:
    addr: http://172.26.98.225:18085/

## 微信相关
wx:
  miniapp:
    configs:
      - appid: wx9d33bcb12eba9f67
        secret: fe687e244a0ed0b4be8835087acc42a0
        token:
        aesKey:
        msgDataFormat:
      - appid: wx594e545a91446cab
        secret: ade9b936c4435a36974e0acb4ff4ee66
        token:
        aesKey:
        msgDataFormat:

dmp:
  socketServer:
    host: www.asiainfo.tech
    port: 9000
logging:
  level:
    root: info
    #com.ai.apac.smartenv.person: debug #打开对应模块的debug日志
