#服务器端口
server:
  port: 8120

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.flow.prod.url}
    username: ${blade.datasource.flow.prod.username}
    password: ${blade.datasource.flow.prod.password}
